develop_front_end:
  description: "Create responsive and user-friendly interfaces."
  expected_output: "A fully functional front-end interface."

develop_back_end:
  description: "Implement server-side logic and database interactions."
  expected_output: "A fully functional back-end system."

full_stack_development:
  description: "Integrate front-end and back-end components."
  expected_output: "A seamlessly integrated application."
  
optimize_and_repair:
  description: "Analyze and improve existing applications."
  expected_output: "Optimized and repaired applications."
  
testing_and_qa:
  description: "Perform thorough testing and debugging."
  expected_output: "A bug-free, high-quality application."
  